version: '3'
services:
  limo_drivers:
    image: lcas.lincoln.ac.uk/lcas/limo_ros_arm64:humble
    user: "ros"
    privileged: true
    command: bash -c "source /opt/ros/lcas/install/setup.bash; (zenoh-bridge-ros2dds -l tcp/0.0.0.0:8888 &); (ros2 launch astra_camera dabai.launch.py &); ros2 launch limo_bringup limo_start.launch.py"
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/agilex/.Xauthority:/home/ros/.Xauthority
    runtime: nvidia
    restart: unless-stopped
    environment:
      - 'DISPLAY=:0'
      - 'ROS_LOCALHOST_ONLY=0'
      - 'LIBGL_ALWAYS_SOFTWARE=1'
      - 'ROS_DOMAIN_ID=0'
      - 'NVIDIA_VISIBLE_DEVICES=all'
    network_mode: host
    cap_add:
        - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
